### ISSUE TITLE
Add Single Datum Generator

### ISSUE THREAD

**Issue by ghost** [Llama-Group/Project-Llama#102]

**Comment by 0xsuu** [comment]
@Giolno Have problems when generating Double. Considering better way to generate single datum. Better with a range instead of a loop(which will cause an infinite loop for double). Also, consider exceptions like the argument passed in is already the greatest value, what will you do? Put an error? Or any other better way? @BlueCocoa

**Comment by 0xsuu** [comment]
PR merged.
